owner: kats1123
repo: Status

sites:
  - name: AIO Metadata
    url: https://aiometadata.jonakats.com
    slug: aio-metadata

  - name: AIO Streams
    url: https://aiostreams.jonakats.com
    slug: aio-streams

  - name: Comet
    url: https://comet.jonakats.com
    slug: comet

  - name: StremThru
    url: https://stremthru.jonakats.com
    slug: stremthru

  - name: NAS
    url: https://nas.jonakats.com
    slug: nas

  - name: Server
    url: https://server.jonakats.com
    slug: server

status-website:
  cname: status.jonakats.com
  name: "Jona Kats Status"
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.png
  introTitle: "Jona Kats Services Status"
  introMessage: This page monitors the uptime of my private services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/kats1123/Status
