owner: kats1123
repo: Status

sites:
  - name: AIO Metadata
    url: $AIOMETADATA_URL

  - name: AIO Streams
    url: $AIOSTREAMS_URL

  - name: Comet
    url: $COMET_URL

  - name: StremThru
    url: https://stremthru.jonakats.com

  - name: NAS
    url: https://nas.jonakats.com

  - name: Proxy
    url: https://proxy.jonakats.com

  - name: Server
    url: $SERVER_URL

status-website:
  cname: status.jonakats.com
  name: JonaKats Status
