# ===============================
# Upptime Configuration
# ===============================
owner: kats1123
repo: Status

skipDeleteIssues: true
workflowSchedule:
  uptime: "*/5 * * * *" 

sites:
  - name: Home Network
    url: "https://homenetwork.jonakats.com:8443/health?token=$GH_PAT"
    slug: home-network-check

  - name: Server 
    url: https://server.jonakats.com
    slug: server

  - name: AIO Metadata - Does Search Work?
    url: https://aiometadata.jonakats.com
    slug: aio-metadata

  - name: AIO Streams - Do Streams have Links?
    url: https://aiostreams.jonakats.com
    slug: aio-streams

  - name: Comet
    url: https://comet.jonakats.com
    slug: comet

  - name: StremThru Torz/Proxy
    url: https://stremthru.jonakats.com
    slug: strem-thru-torz-proxy

status-website:
  cname: status.jonakats.com
  name: "Streaming Service Status"
  introTitle: "Service Status"
  introMessage: "Live uptime and latency for my self-hosted streaming service."
  logoUrl: https://Public:0mn!Ph0t0s@webdav.jonakats.com/Images/omni.png
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/kats1123/Status
  
  customBodyHtml: |
    <script>
      (function () {
        const rewriteStatusBar = () => {
          // Target the bold text inside the status bar
          const statusBox = document.querySelector(".status-bar b") || document.querySelector(".status-bar");
          
          if (statusBox) {
            const text = statusBox.innerText.toLowerCase();
            
            // Logic: If everything is green, it's likely an RD issue or a User issue.
            if (text.includes("all systems are operational")) {
              statusBox.innerHTML = '✅ Still not working? Check <a href="https://debridmediamanager.com/is-real-debrid-down-or-just-me" target="_blank" style="text-decoration: underline; color: inherit;">the website</a>.';
            } 
            
            // Logic: If any outage is detected, provide the link as an extra resource.
            else if (
              text.includes("outage") || 
              text.includes("degraded") || 
              text.includes("major") || 
              text.includes("partial")
            ) {
              statusBox.innerHTML = '❌ Issues detected. You can also check <a href="https://debridmediamanager.com/is-real-debrid-down-or-just-me" target="_blank" style="text-decoration: underline; color: inherit;">the website</a> for RD status.';
            }
          }
        };

        // MutationObserver is the most reliable way to overwrite Svelte's dynamic UI
        const observer = new MutationObserver(rewriteStatusBar);
        observer.observe(document.body, { childList: true, subtree: true });

        // Initial check for the first load
        rewriteStatusBar();
      })();
    </script>
