# ===============================
# Upptime Configuration
# ===============================
owner: kats1123
repo: Status

sites:
  - name: Home Network
    url: "https://homenetwork.jonakats.com:8443/health?token=$GH_PAT"
    slug: home-network-check

  - name: Server 
    url: https://server.jonakats.com
    slug: server

  - name: AIO Metadata - Does Search Work?
    url: https://aiometadata.jonakats.com
    slug: aio-metadata

  - name: AIO Streams - Do Streams have Links?
    url: https://aiostreams.jonakats.com
    slug: aio-streams

  - name: Comet
    url: https://comet.jonakats.com
    slug: comet

  - name: StremThru Torz/Proxy
    url: https://stremthru.jonakats.com
    slug: strem-thru-torz-proxy

status-website:
  cname: status.jonakats.com
  name: "Streaming Service Status"
  introTitle: "Service Status"
  introMessage: "Live uptime and latency for my self-hosted services."
  logoUrl: https://Public:0mn!Ph0t0s@webdav.jonakats.com/Images/omni.png
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/kats1123/Status

  customBodyHtml: |
    <script>
      (function () {
        const injectRD = () => {
          // Prevent duplicates: search for our specific container ID
          if (document.getElementById("rd-status-container")) return;

          const wrap = document.createElement("div");
          wrap.id = "rd-status-container";
          wrap.style.cssText = "margin: 2rem 0; padding: 1rem; border-top: 1px solid #eee; width: 100%;";

          wrap.innerHTML = `
            <h2 style="margin-bottom: 1rem; font-size: 1.5rem; font-weight: bold;">Real-Debrid Status (External)</h2>
            <p style="margin-bottom: 1rem; font-size: 0.9rem; opacity: 0.8;">
              Live status provided by Debrid Media Manager. If not loading, 
              <a href="https://debridmediamanager.com/is-real-debrid-down-or-just-me" target="_blank" style="text-decoration: underline;">click here</a>.
            </p>
            <iframe
              src="https://debridmediamanager.com/is-real-debrid-down-or-just-me"
              style="width: 100%; height: 1000px; border: 1px solid rgba(0,0,0,0.1); border-radius: 12px; background: white;"
              loading="lazy"
            ></iframe>
          `;

          // Find the footer to place the iframe right above it
          const footer = document.querySelector("footer") || document.querySelector(".footer");
          const mainContainer = document.querySelector("main") || document.body;

          if (footer) {
            footer.parentNode.insertBefore(wrap, footer);
          } else {
            mainContainer.appendChild(wrap);
          }
        };

        // Initial run
        if (document.readyState === "complete") {
          injectRD();
        } else {
          window.addEventListener("load", injectRD);
        }

        // MutationObserver handles the "Single Page App" refresh issue
        const observer = new MutationObserver(() => {
          if (!document.getElementById("rd-status-container")) {
            injectRD();
          }
        });

        observer.observe(document.body, { childList: true, subtree: true });
      })();
    </script>
