owner: kats1123
repo: Status

sites:
  - name: AIO Metadata
    url: https://aiometadata.jonakats.com

  - name: AIO Streams
    url: https://aiostreams.jonakats.com

  - name: Comet
    url: https://comet.jonakats.com

  - name: StremThru
    url: https://stremthru.jonakats.com

  - name: NAS
    url: https://nas.jonakats.com

  - name: Proxy
    url: https://proxy.jonakats.com

  - name: Server
    url: https://server.jonakats.com

status-website:
  cname: status.jonakats.com
  name: JonaKats Status
