# ===============================
# Upptime Configuration
# ===============================
owner: kats1123
repo: Status

skipDeleteIssues: true
workflowSchedule:
  uptime: "*/5 * * * *" 

sites:
  - name: Home Network
    url: "https://homenetwork.jonakats.com:8443/health?token=$GH_PAT"
    slug: home-network-check

  - name: Server 
    url: https://server.jonakats.com
    slug: server

  - name: AIO Metadata - Does Search Work?
    url: https://aiometadata.jonakats.com
    slug: aio-metadata

  - name: AIO Streams - Do Streams have Links?
    url: https://aiostreams.jonakats.com
    slug: aio-streams

  - name: Comet
    url: https://comet.jonakats.com
    slug: comet

  - name: StremThru Torz/Proxy
    url: https://stremthru.jonakats.com
    slug: strem-thru-torz-proxy

status-website:
  cname: status.jonakats.com
  name: "Streaming Service Status"
  introTitle: "Service Status"
  introMessage: "Live uptime and latency for my self-hosted streaming service."
  logoUrl: https://Public:0mn!Ph0t0s@webdav.jonakats.com/Images/omni.png
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/kats1123/Status
  
  customBodyHtml: |
    <script>
      (function () {
        const rewriteStatusBar = () => {
          // Target the article tags that Upptime uses for status messages
          const statusArticle = document.querySelector("article.up, article.degraded, article.down");
          
          if (statusArticle && !statusArticle.getAttribute('data-customized')) {
            const text = statusArticle.innerText.toLowerCase();
            
            // If everything is operational
            if (statusArticle.classList.contains('up')) {
              statusArticle.innerHTML = '✅ Still not working? Check <a href="https://debridmediamanager.com/is-real-debrid-down-or-just-me" target="_blank" style="text-decoration: underline; color: #f25287; font-weight: bold;">the website</a>.';
            } 
            // If there is any form of outage
            else {
              statusArticle.innerHTML = '❌ Issues detected. You can also check <a href="https://debridmediamanager.com/is-real-debrid-down-or-just-me" target="_blank" style="text-decoration: underline; color: #f25287; font-weight: bold;">the website</a> for RD status.';
            }
            
            // Mark it so the observer doesn't create an infinite loop
            statusArticle.setAttribute('data-customized', 'true');
          }
        };

        // MutationObserver to handle Svelte's dynamic updates
        const observer = new MutationObserver((mutations) => {
          // If the status bar was replaced or updated by the app, re-run our rewrite
          rewriteStatusBar();
        });

        observer.observe(document.body, { childList: true, subtree: true });

        // Initial run
        rewriteStatusBar();
      })();
    </script>
