# ===============================
# Upptime Configuration
# ===============================
owner: kats1123
repo: Status

sites:

  - name: Home Network Check
    url: "https://homenetwork.jonakats.com:8443/health?token=$GH_PAT"
    slug: home-network-check

  - name: Server 
    url: https://server.jonakats.com
    slug: server

  - name: AIO Metadata - Does Search Work?
    url: https://aiometadata.jonakats.com
    slug: aio-metadata

  - name: AIO Streams -  Do Streams have Links?
    url: https://aiostreams.jonakats.com
    slug: aio-streams

  - name: Comet
    url: https://comet.jonakats.com
    slug: comet

  - name: StremThru Torz/Proxy
    url: https://stremthru.jonakats.com
    slug: strem-thru-torz-proxy

  - name: NAS
    url: https://nas.jonakats.com
    slug: nas

status-website:
  cname: status.jonakats.com
  name: "Welcome to my Status Page"
  introTitle: "Service Status"
  introMessage: "Live uptime and latency for my self-hosted services."
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.png
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/kats1123/Status
status-website:
  cname: status.jonakats.com
  name: "Welcome to my Status Page"
  introTitle: "Service Status"
  introMessage: |
    Live uptime and latency for my self-hosted services.
    
    <div id="dmm-wrapper" style="margin-top: 20px;">
      <iframe 
        id="dmm-iframe"
        src="https://debridmediamanager.com/is-real-debrid-down-or-just-me" 
        style="width:100%; height:1000px; border:none; border-radius:8px; box-shadow: 0 4px 6px rgba(0,0,0,0.1);">
      </iframe>
      
      <script>
        window.addEventListener('load', function() {
          // Find the iframe container and the footer
          var wrapper = document.getElementById('dmm-wrapper');
          var footer = document.querySelector('footer') || document.querySelector('.footer');
          
          if (wrapper && footer) {
            // Move the wrapper to just before the footer
            footer.parentNode.insertBefore(wrapper, footer);
          }
        });
      </script>
    </div>
