# ===============================
# Upptime Configuration
# ===============================
owner: kats1123
repo: Status

sites:

  - name: Home Network Check
    url: "https://homenetwork.jonakats.com:8443/health?token=$GH_PAT"
    slug: home-network-check

  - name: Server
    url: https://server.jonakats.com
    slug: server

  - name: AIO Metadata - Search
    url: https://aiometadata.jonakats.com
    slug: aio-metadata

  - name: AIO Streams -  Stream Options
    url: https://aiostreams.jonakats.com
    slug: aio-streams

  - name: Comet
    url: https://comet.jonakats.com
    slug: comet

  - name: StremThru Torz/Proxy
    url: https://stremthru.jonakats.com
    slug: strem-thru-torz-proxy

  - name: NAS
    url: https://nas.jonakats.com
    slug: nas

status-website:
  cname: status.jonakats.com
  name: "Jona Kats"
  introTitle: "Service Status"
  introMessage: "Live uptime and latency for my self-hosted services."
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.png
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/kats1123/Status
