# ===============================
# Upptime Configuration
# ===============================
owner: kats1123
repo: Status

sites:

  - name: Home Network Check
    url: "https://homenetwork.jonakats.com:8443/health?token=$GH_PAT"
    slug: network-check

  - name: Server 
    url: https://server.jonakats.com
    slug: server

  - name: AIO Metadata - Does Search Work?
    url: https://aiometadata.jonakats.com
    slug: aio-metadata

  - name: AIO Streams -  Do Streams have Links?
    url: https://aiostreams.jonakats.com
    slug: aio-streams

  - name: Comet
    url: https://comet.jonakats.com
    slug: comet

  - name: StremThru Torz/Proxy
    url: https://stremthru.jonakats.com
    slug: strem-thru-torz-proxy

  - name: NAS
    url: https://nas.jonakats.com
    slug: nas

status-website:
  cname: status.jonakats.com
  name: "Welcome to my Status Page"
  introTitle: "Service Status"
  introMessage: "Live uptime and latency for my self-hosted services."
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.png
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/kats1123/Status

  customBodyHtml: |
    <div style="margin: 1rem 0; padding: 1rem; border: 1px solid rgba(0,0,0,.1); border-radius: 12px;">
      <h2 style="margin: 0 0 .5rem 0;">Real-Debrid status (external)</h2>
      <p style="margin: 0 0 .75rem 0;">
        If the embed doesn’t load, open it here:
        <a href="https://debridmediamanager.com/is-real-debrid-down-or-just-me" target="_blank" rel="noopener noreferrer">
          debridmediamanager.com
        </a>
      </p>

      <iframe
        src="https://debridmediamanager.com/is-real-debrid-down-or-just-me"
        style="width: 100%; height: 520px; border: 0; border-radius: 10px;"
        loading="lazy"
        referrerpolicy="no-referrer"
      ></iframe>
    </div>
