# ===============================
# Upptime Configuration
# ===============================
owner: kats1123
repo: Status

skipDeleteIssues: true
workflowSchedule:
  uptime: "*/5 * * * *" 

sites:
  - name: Network
    url: "https://homenetwork.jonakats.com:8443/health?token=$GH_PAT"
    slug: home-network-check

  - name: Server 
    url: https://server.jonakats.com
    slug: server

  - name: AIOMetadata (Search)
    url: https://aiometadata.jonakats.com
    slug: aio-metadata

  - name: AIOStreams (Links)
    url: https://aiostreams.jonakats.com
    slug: aio-streams

  - name: Comet
    url: https://comet.jonakats.com
    slug: comet

  - name: StremThru Torz/Proxy
    url: https://stremthru.jonakats.com
    slug: strem-thru-torz-proxy

status-website:
  cname: status.jonakats.com
  name: "Streaming Service Status"
  introTitle: "Service Status"
  introMessage: |
    Live uptime and latency for my mostly self-hosted streaming service backend.
    <br><br>
    If all systems are operational, and it is still not working, please check <a href="https://debridmediamanager.com/is-real-debrid-down-or-just-me" target="_blank" style="color: #f25287; text-decoration: underline; font-weight: bold;">Real Debrid and Torrentio (☁️) status here</a> and <a href="https://status.debridio.com/" target="_blank" style="color: #f25287; text-decoration: underline; font-weight: bold;">Debridio (🌐) status here</a>.
  logoUrl: https://Public:0mn!Ph0t0s@webdav.jonakats.com/Images/omni.png
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/kats1123/Status
